/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface CommentCount {
    'config': any;
    'shortname': any;
  }
  interface CommentCountAttributes extends StencilHTMLAttributes {
    'config'?: any;
    'shortname'?: any;
  }

  interface CommentEmbed {
    'commentId': any;
    'height': any;
    'showMedia': any;
    'showParentComment': any;
    'width': any;
  }
  interface CommentEmbedAttributes extends StencilHTMLAttributes {
    'commentId'?: any;
    'height'?: any;
    'showMedia'?: any;
    'showParentComment'?: any;
    'width'?: any;
  }

  interface DiscussionEmbed {
    'config': any;
    'shortname': string;
  }
  interface DiscussionEmbedAttributes extends StencilHTMLAttributes {
    'config'?: any;
    'shortname'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'CommentCount': Components.CommentCount;
    'CommentEmbed': Components.CommentEmbed;
    'DiscussionEmbed': Components.DiscussionEmbed;
  }

  interface StencilIntrinsicElements {
    'comment-count': Components.CommentCountAttributes;
    'comment-embed': Components.CommentEmbedAttributes;
    'discussion-embed': Components.DiscussionEmbedAttributes;
  }


  interface HTMLCommentCountElement extends Components.CommentCount, HTMLStencilElement {}
  var HTMLCommentCountElement: {
    prototype: HTMLCommentCountElement;
    new (): HTMLCommentCountElement;
  };

  interface HTMLCommentEmbedElement extends Components.CommentEmbed, HTMLStencilElement {}
  var HTMLCommentEmbedElement: {
    prototype: HTMLCommentEmbedElement;
    new (): HTMLCommentEmbedElement;
  };

  interface HTMLDiscussionEmbedElement extends Components.DiscussionEmbed, HTMLStencilElement {}
  var HTMLDiscussionEmbedElement: {
    prototype: HTMLDiscussionEmbedElement;
    new (): HTMLDiscussionEmbedElement;
  };

  interface HTMLElementTagNameMap {
    'comment-count': HTMLCommentCountElement
    'comment-embed': HTMLCommentEmbedElement
    'discussion-embed': HTMLDiscussionEmbedElement
  }

  interface ElementTagNameMap {
    'comment-count': HTMLCommentCountElement;
    'comment-embed': HTMLCommentEmbedElement;
    'discussion-embed': HTMLDiscussionEmbedElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
